### ISSUE TITLE
Please confirm License of fluent-plugin-multi-format-parser

### ISSUE THREAD

**Issue by NehaSe** [repeatedly/fluent-plugin-multi-format-parser#12]
Please confirm if fluent-plugin-multi-format-parser is licensed under Apache as mentioned here : https://github.com/repeatedly/fluent-plugin-multi-format-parser/blob/master/fluent-plugin-multi-format-parser.gemspec

or MIT has mentioned in the README : https://github.com/repeatedly/fluent-plugin-multi-format-parser/blob/master/README.md

**Comment by netsuvi** [comment]
Unsubscribe

Gesendet mit der GMX iPhone App

Am 19.12.18 um 19:30 schrieb NehaSe

**Comment by repeatedly** [comment]
README is wrong. Just fixed. Thanks!
