### ISSUE TITLE
Error while installing fluent-plugin-multi-format-parser plugin on MapR Cluster 5.2

### ISSUE THREAD

**Issue by nEosAg007** [repeatedly/fluent-plugin-multi-format-parser#5]
I have followed GitHub page to install the plugin and got following error:

./fluent-gem install fluent-plugin-multi-format-parser

Successfully installed fluent-plugin-multi-format-parser-0.1.1
/opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rdoc.rb:572:in `require': cannot load such file -- rdoc/generator/darkfish (LoadError)
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rdoc.rb:572:in `<top (required)>'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:74:in `require'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:74:in `load_rdoc'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:245:in `setup'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:152:in `generate'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:57:in `block in generation_hook'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:56:in `each'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rdoc/rubygems_hook.rb:56:in `generation_hook'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/request_set.rb:186:in `block in install'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `each'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/request_set.rb:185:in `install'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/commands/install_command.rb:250:in `install_gem'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
	from /opt/mapr/fluentd/fluentd-0.14.00/lib/fluentd-0.14.00-linux-x86_64/lib/ruby/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
	from /opt/mapr/fluentd/fluentd-0.14.00/bin/../lib/fluentd-0.14.00-linux-x86_64/lib/app/bin/fluent-gem:6:in `<main>'

Initially, it says "Successfully installed" but then throws the bunch of errors.

Please help

**Comment by repeatedly** [comment]
It seems the problem of mapr, not fluentd.
So I can't help you.

BTW how about using `--no-document`?

**Comment by nEosAg007** [comment]
Hi Masahiro,

Thanks for replying.

 I have solved it by manually copying gem files and its related files from
another machine having td-agent installed.

Then, I corrected correct dependency version in plugins gemspec file. Then
I added gem entries in Gemfile.local

And violla!!

It took several hours to figure that out but at last its working fine.

One more thing on your plugin project page you have mentioned about writing
<filter> section to add patterns for fluentd 00.14 version but mine was not
working but it was working fine with default format i.e. adding patterns in
<source> only.


Thanks and Regards,
Sagar

On Jan 12, 2017 5:05 PM, "Masahiro Nakagawa" <notifications@github.com>
wrote:

It seems the problem of mapr, not fluentd.
So I can't help you.

BTW how about using --no-document?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/repeatedly/fluent-plugin-multi-format-parser/issues/5#issuecomment-272141648>,
or mute the thread

**Comment by repeatedly** [comment]
> mine was not working

I'm not sure but that configuraion assumes latest v0.14.
Did you test it with v0.14.11?

**Comment by nEosAg007** [comment]
It is showing me v0.14.00 on MapR Cluster v5.2.0 with ruby v2.3.0

**Comment by repeatedly** [comment]
I'm not familiar with MapR, so I can't judge  v0.14.00 is fluentd's v0.14.0 or not.
Asking to MapR is better.
